#f=open("external.txt","x")
#f=open("external.txt","w")
f=open("external.txt","a")
f.write("\n")
def externalmark():
    studentreg=input("enter the student register number:")
    f.write(studentreg)
    f.write("\t")
    t1=input("enter the tamil external mark: ")
    f.write(t1)
    f.write("\t")
    e1=input("enter the english external mark: ")
    f.write(e1)
    f.write("\t")
    m1=input("enter the maths external mark: ")
    f.write(m1)
    f.write("\t")
    s1=input("enter the science external mark: ")
    f.write(s1)
    f.write("\t")
    return()
externalmark()
