# import turtle
# s=turtle.Turtle()
# turtle.bgcolor("yellow")
# s.speed(1)
# s.pensize(5)
# s.circle(50)
# s.left(90)
# s.circle(50)
# turtle.done()
#Drawing a rectangle using a graphics
# import turtle
# a=turtle.Turtle()
# turtle.bgcolor("pink")
# a.pensize(5)
# a.speed(1)
# a.forward(500)
# a.dot()
# a.right(90)
# a.forward(100)
# a.dot()
# a.right(90)
# a.forward(500)
# a.dot()
# a.right(90)
# a.forward(100)
# a.dot()
# turtle.done()
#trying letter K
# import turtle
# a=turtle.Turtle()
# turtle.bgcolor("pink")
# a.pensize(5)
# a.speed(1)
# a.penup()
# a.setposition(-30,0)
# a.pendown()
# a.dot()
# a.right(90)
# a.forward(200)
# a.dot()
# a.backward(100)
# a.left(45)
# a.forward(80)
# a.dot()
# a.backward(80)
# a.left(90)
# a.forward(80)
# a.dot()
# turtle.done()
# import turtle
# colors=["pink","yellow","blue","green","violet","red","orange"]
# a=turtle.Pen()
# turtle.bgcolor("black")
# for i in range(360):
#     a.pencolor(colors[i%7])
#     a.width((i/30)+1)
#     a.forward(i)
#     a.left(20)
# turtle.done()
import turtle
import random
a=turtle.Screen()
a.title("lets try a different shape using graphics")
turtle.bgcolor("black")
b=turtle.Turtle()
b.pensize(5)
b.speed(1)
def move():
    b.forward(100)
    b.left(90)
def problem():
    red= random.random()
    blue= random.random()
    green= random.random()
    b.color(red,blue,green)
a.onkeypress(move,"space")
a.onkeypress(problem,"c")
a.listen()
while True:
    move()
    problem()
    a.update()
a.mainloop()