
from tkinter import*
r=Tk()
r.geometry("400x400")
l1=Label(r,text="enter the student name: ")
l1.grid(row=0,column=1)
l2=Label(r,text="enter the student skill: ")
l2.grid(row=1,column=1)
l3=Label(r,text="enter the student place: ")
l3.grid(row=2,column=1)
l4=Label(r,text="enter the student degree: ")
l4.grid(row=3,column=1)
l5=Label(r,text="enter the student qualification: ")
l5.grid(row=4,column=1)

e1=Entry(r)
e1.grid(row=0,column=2)
e2=Entry(r)
e2.grid(row=1,column=2)
e3=Entry(r)
e3.grid(row=2,column=2)
e4=Entry(r)
e4.grid(row=3,column=2)
e5=Entry(r)
e5.grid(row=4,column=2)



def value():
    #f=open("details.txt","x")
    #f=open("details.txt","w")
     f=open("details.txt","a")
     f.write("\n")
     a=str(e1.get())
     f.write(a)
     f.write("\t")
     b=str(e2.get())
     f.write(b)
     f.write("\t")
     c=str(e3.get())
     f.write(c)
     f.write("\t")
     d=str(e4.get())
     f.write(d)
     f.write("\t")
     e=str(e5.get())
     f.write(e)
     f.write("\t")

def delete():
     e1.delete(0,50)
     e2.delete(0,50)
     e3.delete(0,50)
     e4.delete(0,50)
     e5.delete(0,50)     

b=Button(r,text="value",command=lambda:value())
b.grid(row=4,column=4)
b=Button(r,text="delete",command=lambda:delete())
b.grid(row=5,column=5)
r.mainloop()